import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import '../node_modules/react-vis/dist/style.css';
import {XYPlot, LineSeries, VerticalGridLines, HorizontalGridLines, XAxis, YAxis, RadialChart, Sunburst, Hint, LineMarkSeries, GradientDefs} from 'react-vis';

export default function Home() {
  const data = [
    {x: 0, y: 8},
    {x: 1, y: 5},
    {x: 2, y: 4},
    {x: 3, y: 9},
    {x: 4, y: 1},
    {x: 5, y: 7},
    {x: 6, y: 6},
    {x: 7, y: 3},
    {x: 8, y: 2},
    {x: 9, y: 0}
  ];
  const myData = {
    "title": "analytics",
    "color": "#12939A",
    "children": [
     {
      "title": "cluster",
      "children": [
       {"title": "AgglomerativeCluster", "color": "#12939A", "size": 3938},
       {"title": "CommunityStructure", "color": "#12939A", "size": 3812},
       {"title": "HierarchicalCluster", "color": "#12939A", "size": 6714},
       {"title": "MergeEdge", "color": "#12939A", "size": 743}
      ]
     },
     {
      "title": "graph",
      "children": [
       {"title": "BetweennessCentrality", "color": "#12939A", "size": 3534},
       {"title": "LinkDistance", "color": "#12939A", "size": 5731},
       {"title": "MaxFlowMinCut", "color": "#12939A", "size": 7840},
       {"title": "ShortestPaths", "color": "#12939A", "size": 5914},
       {"title": "SpanningTree", "color": "#12939A", "size": 3416}
      ]
     },
     {
      "title": "optimization",
      "children": [
       {"title": "AspectRatioBanker", "color": "#12939A", "size": 7074}
      ]
     }
    ]
   }
   const myData2 = [{angle: 1}, {angle: 5}, {angle: 2}]
  return (
    <div className="App">
<XYPlot height={300} width= {300}>
  <VerticalGridLines />
  <HorizontalGridLines />
  <XAxis />
  <YAxis />
  <LineMarkSeries data={data} />
</XYPlot>
<RadialChart
  data={data}
  width={300}
  height={300} />
<Sunburst
  hideRootNode
  colorType="literal"
  data={myData}
  height={300}
  width={350}>
   
</Sunburst>
  {/* <Hint value={hoveredValue} */}
  <RadialChart
        colorType={'literal'}
        colorDomain={[0, 100]}
        colorRange={[0, 10]}
        margin={{top: 100}}
        getColor={d => `url(#${d.gradientLabel})`}
        data={[
          {angle: 1, gradientLabel: 'grad1'},
          {angle: 2, gradientLabel: 'grad2'},
          {angle: 5, gradientLabel: 'grad3'}
        ]}
        labelsRadiusMultiplier={1.1}
        labelsStyle={{fontSize: 16, fill: '#222'}}
        showLabels
        style={{stroke: '#fff', strokeWidth: 2}}
        width={400}
        height={300}>
        <GradientDefs>
          <linearGradient id="grad1" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stopColor="red" stopOpacity={0.4}/>
            <stop offset="100%" stopColor="blue" stopOpacity={0.3} />
          </linearGradient>
          <linearGradient id="grad2" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stopColor="blue" stopOpacity={0.4}/>
            <stop offset="100%" stopColor="green" stopOpacity={0.3} />
          </linearGradient>
          <linearGradient id="grad3" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stopColor="yellow" stopOpacity={0.4}/>
            <stop offset="100%" stopColor="green" stopOpacity={0.3} />
          </linearGradient>
        </GradientDefs>
      </RadialChart>
    </div>
  );
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/canary/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // )
}
